### PR TITLE
New Section: Contribution needed.

### PR DESCRIPTION
**Pull request by pedrommcarrasco**
During my journey through RxSwift I had the challenge to work with web sockets in a professional project. I found RxStarscream on github and then I saw it wasn't ready for RxSwift 4 and Swift 4.
I saw Shai was the one responsible for the latests updates and decided to talk with him, asking permissions to update it. Oh well, I've managed to do it with his help in later stages (code review and CI) and it was also my first contribution to anything outside of personal projects of mine. I've managed to learn more about DelegateProxy and CircleCi while establishing contact with Shai.

Where do I want to get?
There are some repositories in need of people to update them, share and learn in the process. I think that with this section we could highlight repositories that are with issues and others that might need an upgrade for Swift 4 for example (and if the tradition stays the same, Swift 5 later this year 🎉 ). Old code is a problem and I think we should try to avoid losing frameworks like ImagePicker during Swift's evolution.

### CODE REVIEW

**Comment by freak4pc** [comment]
Hey @pedrommcarrasco 
Great discussion ! 

I totally understand and see the need to do something like this, but I don't think the website is the right place to do a "looks for contributions" thing, since everything needs contributions, constantly :) 

What works well IMO is using tags like `help needed` or `good first contribution`. Then we can add on the website some text on top saying: "Most projects listed in this website are entirely built and maintained by the community. Want to help? We could always use your help!" 

And have that last sentence linking to page that lists issues with these tags.

Another interesting options is to actually present a count (or colored badge) based on the number of issues marked with these tags, and tapping those would link to these issues. 

I actually kinda like this last option. I'm sort of against adding an entire section just for it as I feel its not generic enough and also not automated enough (you would have to constantly maintain this list).

What do you think?

**Comment by pedrommcarrasco** [comment]
The problem around my solution was exactly what you pointed out, first it was not automated enough and would require multiple commits to maintain it. Second I had the same problem thinking that the section itself was out of place, but my point was, I liked the idea of having any part of the site or metric that would point out something like: "Hey guys! Do you have some free time? Are you trying to use a framework in a project but it doesn't work? Come here and help, we have challenges for everyone" because RxSwift was built by people and it should be maintained by people. From what I know nobody was paid to do it and nobody is getting paid to do it also, so we should get as many hands as we could. (I'm pretty small on the community so tell me if I'm wrong!)

"What works well IMO is using tags like help needed or good first contribution. Then we can add on the website some text on top saying: "Most projects listed in this website are entirely built and maintained by the community. Want to help? We could always use your help!"" 👍 
"Another interesting options is to actually present a count (or colored badge) based on the number of issues marked with these tags, and tapping those would link to these issues." 👍 

In my opinion the perfect solution would be both of them, benefits? Issue opening would follow the same patterns across RxSwiftCommunity (at least) and the whole process of the website being updated could be automated (my knowledge in web is really (REALLY 👎 ) limited but if I can help with anything it would be fun :D)

Anyways the main goal is here, create a discussion and find the best way to get people in!

**Comment by freak4pc** [comment]
> In my opinion the perfect solution would be both of them

Absolutely agree. 

Here is my proposed solution for this issue: 

1. Mark issues with `needs help` and `good first contribution` (this is something you can definitely help with in the "moderation" side, if you have the time or just see an issue without a tag). 

2. On the web side, have the script populate the number of issues as well, and then we can have a colored badge (red, orange, yellow, green) based on the number of open issues that need external help (for example green: 0, yellow, 0-3, orange: 3-10, red: >10, but we can experiment with these numbers later).

Seems like a proper solution to me :) We can also add an explanation on the top of the page so people understand these badges, and they would link directly to the issues that need help (e.g. marked with these tags). 

Let me know what do you think :)

**Comment by freak4pc** [comment]
P.S this showed up on GitHub a while ago, so adding these labels would be even better: 

31588172-37d2b4d8-b1e6-11e7-9e3c-335fe1ad0574

**Comment by pedrommcarrasco** [comment]
The timing of those labels was incredible but yeah that sounds great since both "Help wanted" and "Good First Issue" are pretty much what we are looking for.

The step 1 would probably be the first one, I could for example open issues in RxState and RxMediaPicker as "good first issue" for a RxSwift 4/Swift 4 update.

The step 2 would probably be the hardest to me but could I try to help with something or at least learn from it, but alone I think I'm not able to do it. I'm not quite sure about the colors tho, it could get some people afraid by seeing red all over their screen. So in my opinion just display an help wanted icon if it has any "Help wanted" issue. The same logic goes for "Good first Issue"

The latest part would be pretty neat, but for example if you have 2 issues of the same type it would be hard to point out the references, so maybe they should all point to the "Issues" page.

**Comment by freak4pc** [comment]
@pedrommcarrasco Colors can be something else. It's definitely something we can consider, but TBH its also good for people to understand whether or not a project is active or highly inactive. 

We can start the second part to target _all_ issues, and later switch to only issues with these tags, when we add them. Also a possibility.

**Comment by pedrommcarrasco** [comment]
Sound like a good start, do you have any knowledge on the web part of this?

**Comment by freak4pc** [comment]
Yeah :) I did the new meta data part. I'm gonna close this and open a discussion in a separate issue.

**Pull request closed without merging**
