### PR TITLE
RxTodo-app added

### PR DESCRIPTION
**Pull request by cagricolak**
This project using RxSwift, MVVM-C and https://jsonplaceholder.typicode.com/ for dummy json response

### CODE REVIEW

**Comment by ashfurrow** [comment]
Cool! Makes sense – about time we added a TODO app! Before we merge this PR, could you please add a README and LICENSE to your repository? It will help orient other developers, as well as given them legal permission to use the code that you've contributed to the community.

Let me know when those are in and we can merge this PR 👍 Thanks again!

**Comment by freak4pc** [comment]
We actually already have RxTodo :) Maybe better giving it a different name so it doesn't confuse people? 
image

**Comment by cagricolak** [comment]
@freak4pc yes I saw it, but this project has a more modern interface and was written with more user interaction. when i prepare the read me document, the difference can be understood more clearly.

**Comment by cagricolak** [comment]
@ashfurrow repo updated.

**Comment by ashfurrow** [comment]
Hey! Sorry for the delay in responding it's been a busy week 😅 

The repo looks great 💯 Any reason to close this instead of merging?

**Comment by cagricolak** [comment]
@ashfurrow no don't have ant reason.

**Comment by ashfurrow** [comment]
🎉

**Pull request merged**
