### PR TITLE
adds rxfeedback and rxanimated

### PR DESCRIPTION
**Pull request by icanzilb**
adds two more libs to the list

### CODE REVIEW

**Comment by kzaher** [comment]
👍

**Comment by icanzilb** [comment]
@freak4pc the changes don't show up on the web site for me .. do you see them?

**Comment by freak4pc** [comment]
@icanzilb Uhm `source` build looks good - https://travis-ci.org/RxSwiftCommunity/rxswiftcommunity.github.io/builds/294081351

We'll probably needs @ashfurrow's help here

**Comment by ashfurrow** [comment]
Looks like the changes _were_ deployed but then got removed from `index.html` in this commit: https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io/commit/d36d2a1eab12dd644d460ecc10bade3fb4c572df Not sure what happened there. 

Since the `source` files were good, I pushed an [empty commit to `source`](https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io/commit/40f1aa80b74aa5ea54033e7edda7914717c0cba7) which resulted in a [commit to `master`](https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io/commit/6bdb0caef967e8c0546e9b3f2d13ebf86b5496f0) that re-deployed these changes. Things on http://community.rxswift.org look good to me 👍

**Comment by freak4pc** [comment]
Thanks @ashfurrow !

**Comment by ashfurrow** [comment]
I will add that this is exactly the kind of situation I'm trying to make easier in this issue: https://github.com/RxSwiftCommunity/contributors/issues/27 In the course of working in the open source community, it's often really useful to know who to turn to. Someone who isn't familiar with the organization would probably feel lost in this situation, and I don't want to alienate anyone from the community.

**Pull request merged**
