### PR TITLE
Updated autodeploys

### PR DESCRIPTION
**Pull request by ashfurrow**
Continued from #6.

### CODE REVIEW

**Comment by esttorhe** [comment]
screen shot 2015-12-17 at 5 11 06 p m

:ok_hand:

**Comment by ashfurrow** [comment]
Hmm, odd it's still failing...

**Comment by esttorhe** [comment]
it worked before the merge; now its failing again :/

**Comment by esttorhe** [comment]
```
error: The following untracked working tree files would be overwritten by checkout:
	images/background.png
	images/middleman.png
	index.html
	javascripts/all.js
	stylesheets/all.css
	stylesheets/normalize.css
```

**Comment by ashfurrow** [comment]
Yeah, it's only the actual deploy (which it only does after merging). 

Could be this issue: https://github.com/edgecase/middleman-gh-pages/issues/20

**Pull request merged**
