### PR TITLE
Fixes deploys.

### PR DESCRIPTION
**Pull request by ashfurrow**
Picking up from #7.

### CODE REVIEW

**Comment by esttorhe** [comment]
Would the `publish` task will build as well?

**Comment by ashfurrow** [comment]
Yes exactly! 

Now I'm getting a different error ...

**Comment by ashfurrow** [comment]
Might've been a permissions problem with the personal access token I encrypted.

**Comment by ashfurrow** [comment]
Nope, just me being silly and misconfiguring `.travis.yml`.

**Comment by ashfurrow** [comment]
Pushed https://github.com/RxSwiftCommunity/rxswiftcommunity.github.io/commit/9e8496f9c61ee13e18bc0dfdf1f2f91f7c9c9c93 onto `source`

**Comment by esttorhe** [comment]
:confetti_ball: !!!

**Comment by esttorhe** [comment]
I broke it with #10 apparently :(

```
*** Please tell me who you are.
Run
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: empty ident name (for <travis@testing-worker-linux-docker-2790f3de-3206-linux-5.prod.travis-ci.org>) not allowed
rake aborted!
```

**Pull request merged**
