### PR TITLE
Add CNAME file to point to community.rxswift.org

### LINKED ISSUE #9: Add CNAME file to support community.rxswift.org
The DNS CNAME record has been created and points to rxswiftcommunity.github.io.
Adding the CNAME file will make the website available at community.rxswift.org.

### PR DESCRIPTION
**Pull request by psophis**
Fixes #9

### CODE REVIEW

**Comment by psophis** [comment]
As per: https://github.com/edgecase/middleman-gh-pages#custom-domain

**Comment by esttorhe** [comment]
:tada:

**Comment by psophis** [comment]
Uh oh! https://travis-ci.org/RxSwiftCommunity/rxswiftcommunity.github.io/builds/97572660

**Comment by ashfurrow** [comment]
I'll take a look!

**Comment by ashfurrow** [comment]
Very strange – looks like [this problem](http://stackoverflow.com/questions/24850247/git-post-receive-hook-empty-ident-name). I'll fix in my branch.

**Pull request merged**
