### PR TITLE
Adds basic design

### LINKED ISSUE #1: Use Github pages
This is here for further discussion related using Github pages.

### LINKED ISSUE #2: Add repos from original issue
This is more of a "todo" once we have it figured out where/what this repo will be.

https://github.com/RxSwiftCommunity/contributors/issues/5

### LINKED ISSUE #4: Define what is needed for a project and add to contributing section in README
Title, link, description, etc...

Authorization from project owner?

### PR DESCRIPTION
**Pull request by ashfurrow**
Looks like the following:

screen shot 2015-12-17 at 8 01 01 pm

screen shot 2015-12-17 at 8 01 03 pm

You can add more projects in the `items.yml` file. 

Next steps are to make it pretty, but I may be done for the night.

Fixes #1.
Fixes #2.
Fixes #4.

### CODE REVIEW

**Comment by ashfurrow** [comment]
I also added in the libraries collected so far in #2.

**Comment by ashfurrow** [comment]
Made it prettier too:

screen shot 2015-12-17 at 8 54 04 pm

We can change the design, layout, colours, anything we want!

**Comment by esttorhe** [comment]
I'm liking it!!

Assuming this is not a `WIP` so i'm going to pull the trigger and merge

**Comment by psophis** [comment]
👍👍 Very nice! This is coming along nicely!

**Pull request merged**
