### PR TITLE
Update README logo src to absolute url

### PR DESCRIPTION
**Pull request by psophis**

### CODE REVIEW

**Comment by psophis** [comment]
Crap. That didn't work either.

**Comment by esttorhe** [comment]
I think there are 2 "source"s in the path

**Comment by psophis** [comment]
One is the branch the other is the directory. It's the content type that's wrong.

http://stackoverflow.com/questions/13808020/include-an-svg-hosted-on-github-in-markdown

**Comment by esttorhe** [comment]
Forgot that the branch was called source as well

**Pull request closed without merging**
